### ISSUE TITLE
Add to our addon galary

### ISSUE THREAD

**Issue by arunoda** [sm-react/storybook-addon-material-ui#1]
This is so cool.
Is this project ready?
Then I can add it to our addon galary on docs.

If not, just let me know when it's ready.

**Comment by UsulPro** [comment]
Thank you! It would be great!
I think I need a bit to finish.
And I'll let you know when it's ready.

**Comment by arunoda** [comment]
Cool.

**Comment by UsulPro** [comment]
https://getstorybook.io/docs/addons/addon-gallery
:thumbsup:
