### ISSUE TITLE
Add react-split-pane package

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#13]
Sinse react-split-pane was published on NPM we could add it as dependency and remove this clone:
[src/components/SplitPane](https://github.com/sm-react/storybook-addon-material-ui/tree/master/src/components/SplitPane)
NPM package: https://www.npmjs.com/package/react-split-pane

place to start: [src/containers/MuiTheme](https://github.com/sm-react/storybook-addon-material-ui/blob/master/src/containers/MuiTheme.js#L159)

**Comment by xRahul** [comment]
Hey @UsulPro 
I'm going to try this one.. let me know what you think!

**Comment by xRahul** [comment]
Hey,

I've made the changes and committed the code here- https://github.com/xRahul/storybook-addon-material-ui/commit/23da638250b690c394cb57cebb85e5d7a3bf533d

But I'm getting errors running the `cmd` scripts when running `npm i`.
Can you help me out with them?

**Comment by xRahul** [comment]
I've created a shell script for the cmd script that was throwing the error.

Final PR- https://github.com/sm-react/storybook-addon-material-ui/pull/14

**Comment by UsulPro** [comment]
Sure!
possible errors due to windows `cmd` scripts?

**Comment by xRahul** [comment]
yeah I have a bash shell, so I created a `prepublish.sh` script for the npm install to run successfully. I haven't changed it in the package.json, but for future work on bash, dev can just change the script in prepublish and work on it
