### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Domiii** [sm-react/storybook-addon-material-ui#17]
Hi!

`material-ui` now has `v0.16` but you still require `v0.15.4` :)

**Comment by UsulPro** [comment]
[Sure](https://github.com/sm-react/storybook-addon-material-ui/commit/ddaff67f8d7097663ae0c34318228ea0fbe2341f) Thank you!

**Comment by Domiii** [comment]
You forgot to bump the version <3
