### ISSUE TITLE
Theme panel not visible

### ISSUE THREAD

**Issue by makstr** [sm-react/storybook-addon-material-ui#18]
Hi I am looking into your repo, how do you invoke theme panel in the right pane? I tried to alter .storybook/config.js

```
import * as storybook from '@kadira/storybook';
import { setOptions } from '@kadira/storybook-addon-options';

setOptions({
  name: 'sm-react',
  url: 'https://github.com/sm-react/storybook-addon-material-ui',
  goFullScreen: false,
  showLeftPanel: false,
  showDownPanel: false,
  showSearchBox: false,
  downPanelInRight: true, // here?
});

storybook.configure(() => require('./../example/stories/'), module);
```

**Comment by UsulPro** [comment]
Hi @makstr! To open right panel use the `Show Theme Editor` switcher at the right of down panel:

![image](https://cloud.githubusercontent.com/assets/14885189/19391831/74a92706-9258-11e6-896a-08c05f9b715e.png)

If this is not what you are asking, please, give me more details

**Comment by UsulPro** [comment]
sorry @makstr it was really bug. now it [fixed](https://github.com/sm-react/storybook-addon-material-ui/commit/3e55204c78b8c57ff0935b5849c28615f2e0afe7)
