### ISSUE TITLE
How to override default light theme?

### ISSUE THREAD

**Issue by achtan** [sm-react/storybook-addon-material-ui#2]
Hi, how to override default light theme?

**Comment by UsulPro** [comment]
@achtan! 
When you pass any theme object to muiTheme decorator it creates a new theme based on the default light theme. (like second examle in [Getting Started](https://github.com/sm-react/storybook-addon-material-ui#getting-started)) Only the specified properties will be overwritten and you can see them in right sidebar panel. 

I hope I answered your question, but reopen this issue, if that's not what you are looking for.

**Comment by achtan** [comment]
my decoretor
````
import {muiTheme} from 'storybook-addon-material-ui';
import {deepPurple500, orange700} from 'material-ui/styles/colors';

const newTheme = {
  palette: {
    primary1Color: deepPurple500,
    accent1Color: orange700,
  },
  appBar: {
    height: 56,
  },
};

addDecorator(muiTheme(newTheme));
````
But in Storybook > Material UI tab I see 3 themes `Light Theme`, `Dark Theme` and `Theme 3`.

**Comment by UsulPro** [comment]
Right, at the moment this is expected behavior:
we allways have this two themes by default and then goes all custom themes.
`Theme 3` is your overriden theme.
May be we need an option to exclude default themes? 

On the other hand in v0.7 we'll be able to specify the theme in the address bar so you don't need to switch it each time.

**Comment by achtan** [comment]
it would be nice to have control over themes... for example i need only one theme, i dont need dark theme... i need only modified light theme

**Comment by achtan** [comment]
in fact, there is no reason to have 'default light theme' if i specify my custom theme...

**Comment by UsulPro** [comment]
**Done!**
Now default themes appears only if you don't specify any custom theme
