### ISSUE TITLE
Сreate a simple React Component #hacktoberfest

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#20]
#### due [this](https://github.com/sm-react/storybook-addon-material-ui/issues/19)

we need simple React Component including [card](http://www.material-ui.com/#/components/card), [buttons](http://www.material-ui.com/#/components/flat-button) and some [text](http://www.material-ui.com/#/components/card)
#### Steps to start
- [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)
- clone your repo to local machine and install

```
git clone https://github.com/YOUR-NAME/storybook-addon-material-ui.git
cd storybook-addon-material-ui
npm i
npm start
```
- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`.
- Check eslint.

```
npm run lintMaterial
```
- Push your ready project to github:

```
git commit -m «my ready to PR story»
git push

```
- Make  Pull request from your Github repo.

See details [here](https://github.com/sm-react/storybook-addon-material-ui/blob/master/example/LoremMaterial/doc/LoremMaterial.md)

**Comment by andela-ijubril** [comment]
Hi @UsulPro, I would like to jump on this.

**Comment by UsulPro** [comment]
Ok @andela-ijubril 
ask if you will need help

**Comment by andela-ijubril** [comment]
Hi @UsulPro 

- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`

What component am I to create?
Thanks

**Comment by UsulPro** [comment]
@andela-ijubril it is like a creative task
>we need simple React Component including card, buttons and some text

kind of such http://www.louistiti.fr/demo/Concept-Design/Carte-Article-UI/

**Comment by UsulPro** [comment]
Hi @andela-ijubril 
I was just wondering how things are going with it.
Just let me know whether you still working on it?
