### ISSUE TITLE
fake travel date picker React Component #hacktoberfest

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#21]
**why we [neeed ](https://github.com/sm-react/storybook-addon-material-ui/issues/19) this**

create React Component looking like airline booking element:
- selecting `depart date`, `return date` [date-picker](http://www.material-ui.com/#/components/date-picker)
- `return` -  `one way` switcher [switcher](http://www.material-ui.com/#/components/toggle)
- `origin`, `destination` selects [select-field](http://www.material-ui.com/#/components/select-field}
- `number of travellers` 
- `search`  button [buttons](http://www.material-ui.com/#/components/raised-button)

>:airplane: [looking for inspiration?](https://www.google.ru/webhp?hl=ru&tab=yw#newwindow=1&hl=ru&q=book%20flight)

**Steps to start**
- [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)
- clone your repo to local machine and install
```
git clone https://github.com/YOUR-NAME/storybook-addon-material-ui.git
cd storybook-addon-material-ui
npm i
npm start
```
- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`.
- Check eslint.
```
npm run lintMaterial
```
- Push your ready project to github:
```
git commit -m «my ready to PR story»
git push

```
- Make  Pull request from your Github repo.

See details [here](https://github.com/sm-react/storybook-addon-material-ui/blob/master/example/LoremMaterial/doc/LoremMaterial.md)

**Comment by S4KH** [comment]
Hi, is it just a component(meaning just the front-end)? Or we also have to some stuff when button is pressed?

**Comment by UsulPro** [comment]
@S4KH Yes just isolated front-end component.
but, you may implement some behavior within react class, if you want (like state for oneway/return fly)

**Comment by S4KH** [comment]
@UsulPro Thanks for the quick response :+1: 
In which **folder** I have to create my component and how to _demo_ it?

**Comment by S4KH** [comment]
Did something like this: 
![selection_006](https://cloud.githubusercontent.com/assets/15072209/19461603/85cca806-9518-11e6-8b15-93f56deb9753.png)
![screenshot from 2016-10-18 09-52-51](https://cloud.githubusercontent.com/assets/15072209/19461625/bcbc0c08-9518-11e6-8ef9-f06b305ba5e0.png)


Used `AutoComplete` for searching `from` and `to` cities.

**Comment by UsulPro** [comment]
@S4KH Thank you! It's cool! Right what we need!

**Comment by UsulPro** [comment]
[published](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=Airline%20booking&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)
@S4KH I just removed black color of labels since we need to support all themes
