### ISSUE TITLE
Login Page Imitation #hacktoberfest

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#22]
**why we [neeed ](https://github.com/sm-react/storybook-addon-material-ui/issues/19) this**

create a simple login simulating page:
- login and password fields [text-field](http://www.material-ui.com/#/components/text-field)
- login/signUp buttons, get creative

>:key: [where to get inspiration?](https://www.google.com/webhp?hl=ru&tab=yw#newwindow=1&hl=ru&q=login)

**due to the fact that we need to cover all elements of [Material-UI](http://www.material-ui.com/#/components) you are welcome to offer your own idea for a page**

You can start from editing this [template](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=blank%20page&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

**Steps to start**
- [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)
- clone your repo to local machine and install
```
git clone https://github.com/YOUR-NAME/storybook-addon-material-ui.git
cd storybook-addon-material-ui
npm i
npm start
```
- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`.
- Check eslint.
```
npm run lintMaterial
```
- Push your ready project to github:
```
git commit -m «my ready to PR story»
git push

```
- Make  Pull request from your Github repo.

See more details in [LoremMaterial/doc/LoremMaterial.md](https://github.com/sm-react/storybook-addon-material-ui/blob/master/example/LoremMaterial/doc/LoremMaterial.md)

>not sure that ready to start? [watch](https://github.com/sm-react/storybook-addon-material-ui/subscription) us, we publish new #hacktoberfest tasks every day

**Comment by minibhati93** [comment]
I am not quite familiar with React. Can I still work on this?

**Comment by UsulPro** [comment]
@minibhati93 you can try your hand as it is a special task for beginners. Look at these [examples](http://www.material-ui.com/#/components/text-field). Try to create something simple to start. You are always welcome to ask questions

**Comment by austinvernsonger** [comment]
Need help on this?

**Comment by UsulPro** [comment]
Yes we need. @austinvernsonger, @minibhati93 you may make your own version of Login Page
or choose any other task of this type: [#19]

**Comment by UsulPro** [comment]
@minibhati93, @austinvernsonger how are you doing?
I was just wondering did you take this task and whether you need any help with this?

**Comment by minibhati93** [comment]
Hi @UsulPro. I am working on this task. Apologies for not being active. I'm  unable to run in the browser and facing some issues. I forked the repository and tried `npm i` and finally `npm start`. Could you please guide me on this? 
![screen shot 2016-10-28 at 3 32 50 pm](https://cloud.githubusercontent.com/assets/5766372/19803061/48f26ac4-9d24-11e6-9c34-4080b22e9732.png)

**Comment by UsulPro** [comment]
@minibhati93 I suppose the best way to start fixing it is to jump to the latest ver of the project.
you can make a PR from my repo to your fork or just remove it and fork again. After that make new `git clone` and `npm i`
if any errors still will appears could you give me more details?

- you OS
- you node and npm ver (`node -v' and 'npm -v')
- you browser ver
