### ISSUE TITLE
Contact List Imitation #hacktoberfest

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#24]
**why we [neeed ](https://github.com/sm-react/storybook-addon-material-ui/issues/19) this**

create a contact list component:
- should have a [list](http://www.material-ui.com/#/components/list) of users
- with [avatar](http://www.material-ui.com/#/components/avatar), name, phone number
(all fake datas)

>:calling: [find inspiration!](http://bit.ly/contactlistandroid)

**due to the fact that we need to cover all elements of [Material-UI](http://www.material-ui.com/#/components) you are welcome to offer your own idea for a page**

You can start from editing this [template](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=blank%20page&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

**Steps to start**
- [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)
- clone your repo to local machine and install
```
git clone https://github.com/YOUR-NAME/storybook-addon-material-ui.git
cd storybook-addon-material-ui
npm i
npm start
```
- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`.
- Check eslint.
```
npm run lintMaterial
```
- Push your ready project to github:
```
git commit -m «my ready to PR story»
git push

```
- Make  Pull request from your Github repo.

See more details in [LoremMaterial/doc/LoremMaterial.md](https://github.com/sm-react/storybook-addon-material-ui/blob/master/example/LoremMaterial/doc/LoremMaterial.md)

>not sure that ready to start? [watch](https://github.com/sm-react/storybook-addon-material-ui/subscription) us, we publish new #hacktoberfest tasks every day

**Comment by luongthomas** [comment]
I am interested in helping!

**Comment by UsulPro** [comment]
@luongthomas Ok

**Comment by kasperwf** [comment]
I would also love to give it a try.

**Comment by luongthomas** [comment]
![screen shot 2016-10-24 at 11 27 12 am](https://cloud.githubusercontent.com/assets/11577853/19658446/ded110e0-99dc-11e6-9dd8-884839108047.jpeg)

What do you think of what I have so far?

**Comment by UsulPro** [comment]
Yes, it's cool!

**Comment by luongthomas** [comment]
Pull request #30 

Thanks!

**Comment by UsulPro** [comment]
Published: [Contact List](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=1&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=Contact%20List&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)
👍
