### ISSUE TITLE
Fake Chat Conversation React Component #hacktoberfest

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#25]
why we [neeed ](https://github.com/sm-react/storybook-addon-material-ui/issues/19) this
### create React Component looking like short part of mobile chat conversation

> - should have a [list](http://www.material-ui.com/#/components/list) with some messages
> - [avatars](http://www.material-ui.com/#/components/avatar)
> - [input field](http://www.material-ui.com/#/components/text-field)

 in general should look like [this](http://bit.ly/contactlistandroid) 📝

here are a few already done examples of this library:
[https://sm-react.github.io/storybook-addon-material-ui/](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=Hactoberfest%20issues%3A&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

look for other similar [open tasks](https://github.com/sm-react/storybook-addon-material-ui/issues?q=is%3Aissue+is%3Aopen+label%3Adesign)

See more details in [LoremMaterial/doc/LoremMaterial.md](https://github.com/sm-react/storybook-addon-material-ui/blob/master/example/LoremMaterial/doc/LoremMaterial.md)

> not sure that ready to start? [watch](https://github.com/sm-react/storybook-addon-material-ui/subscription) us, we publish new #hacktoberfest tasks every day

**due to the fact that we need to cover all elements of [Material-UI](http://www.material-ui.com/#/components) you are welcome to offer your own idea**

You can start from editing this [template](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=blank%20page&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

**Steps to start**
- [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)
- clone your repo to local machine and install

```
git clone https://github.com/YOUR-NAME/storybook-addon-material-ui.git
cd storybook-addon-material-ui
npm i
npm start
```
- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`.
- Check eslint.

```
npm run lintMaterial
```
- Push your ready project to github:

```
git commit -m «my ready to PR story»
git push

```
- Make  Pull request from your Github repo.

**Comment by sanketmaru** [comment]
@UsulPro  I can help on this.

**Comment by UsulPro** [comment]
Cool!

**Comment by UsulPro** [comment]
Hey @sanketmaru , how are you doing?
You self-assigned this issue more than a week ago. I was just wondering how things are going with it, and whether you need any help.

**Comment by sanketmaru** [comment]
@UsulPro  I have started on this , will surely let you know if needed any help.

**Comment by sanketmaru** [comment]
@UsulPro I have created a component and it looks like the one in attached. 

I have created one Message component which accepts props such as it is a sender or a receiver and the text of the message. 

The messages can then be embedded into the Conversation Chat Component. 

Do let me know what you think ?

![conversation_chat](https://cloud.githubusercontent.com/assets/7148430/19893201/5514d4f2-a06e-11e6-818b-ec07af21b7f4.png)

**Comment by UsulPro** [comment]
@sanketmaru I think in general you are on the right direction! I like it, but there are some issues:
Could you wrap text messages into some color fields?
May be we could display avatars near every message?
And show time as well (to represent more colors from the palette)
I think input field should have `marginLeft: 16` or better to put in inside the `CardText`

**Comment by sanketmaru** [comment]
@UsulPro I have done the changes and created the PR(https://github.com/sm-react/storybook-addon-material-ui/pull/48) , please verify it. Below is the screen shot of how it looks currently.

![conversation_chat](https://cloud.githubusercontent.com/assets/7148430/19939969/1005286a-a151-11e6-94d2-68b8e19c11ae.png)

**Comment by UsulPro** [comment]
@sanketmaru is it possible to align text and time in message?

**Comment by sanketmaru** [comment]
Do we want text and time in the same line ? Currently i have added timestamp as a subscript.

**Comment by UsulPro** [comment]
maybe we could put it outside this field and another color? 
something like in this image https://www.google.co.th/search?q=contact+list+android&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjJ6rqZ2OTPAhWMo48KHUtjDHMQ_AUICCgB&biw=1918&bih=990&gws_rd=cr&ei=RecaWJPYCIHlvATtvJfgCA#newwindow=1&tbm=isch&q=text+message&imgrc=yt6zjAZKcssM0M%3A

**Comment by sanketmaru** [comment]
@UsulPro I have fixed the alignment. Please verify.

![conversation_chat](https://cloud.githubusercontent.com/assets/7148430/20028283/408285c4-a353-11e6-8451-06ea09017773.png)
