### ISSUE TITLE
Сreate a `Pizza oder` React Component #hacktoberfest

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#29]
why we [neeed ](https://github.com/sm-react/storybook-addon-material-ui/issues/19) this
### You need to create a component that demonstrates the behavior of the form to order a pizza and contains the necessary elements

> - should based on [material-ui](http://www.material-ui.com)

 ideas for what should it be [![image](https://cloud.githubusercontent.com/assets/14885189/19624327/e56a3426-991a-11e6-9281-3a8d47fcd48d.png)
](http://bit.ly/pizzaoder) 

here are a few already done examples of this library:
[https://sm-react.github.io/storybook-addon-material-ui/](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=Hactoberfest%20issues%3A&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

look for other similar [open tasks](https://github.com/sm-react/storybook-addon-material-ui/issues?q=is%3Aissue+is%3Aopen+label%3Adesign)

See more details in [LoremMaterial/doc/LoremMaterial.md](https://github.com/sm-react/storybook-addon-material-ui/blob/master/example/LoremMaterial/doc/LoremMaterial.md)

> not sure that ready to start? [watch](https://github.com/sm-react/storybook-addon-material-ui/subscription) us, we publish new #hacktoberfest tasks every day

**due to the fact that we need to cover all elements of [Material-UI](http://www.material-ui.com/#/components) you are welcome to offer your own idea**

You can start from editing this [template](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&theme-full=false&selectedKind=Material%20App&selectedStory=blank%20page&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

**Steps to start**
- [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)
- clone your repo to local machine and install

```
git clone https://github.com/YOUR-NAME/storybook-addon-material-ui.git
cd storybook-addon-material-ui
npm i
npm start
```
- Create your React Component from this file `example/LoremMaterial/blankMaterialAppExampleProgress.jsx`.
- Check eslint.

```
npm run lintMaterial
```
- Push your ready project to github:

```
git commit -m «my ready to PR story»
git push

```
- Make  Pull request from your Github repo.

**Comment by vincealdrin** [comment]
I will try to work on this today

**Comment by UsulPro** [comment]
Ok @vincealdrin 
Ask any questions if you'll need a help

**Comment by UsulPro** [comment]
@vincealdrin how are you doing?
I was just wondering did you still on this task and whether you need any help with this?

**Comment by vincealdrin** [comment]
@UsulPro Sorry, I stopped working on it at the moment but I will submit a PR within next week
