### ISSUE TITLE
Pane is not scrollable

### ISSUE THREAD

**Issue by achtan** [sm-react/storybook-addon-material-ui#3]
add `overflow: scroll` to `div.Pane vertical Pane1`

**Comment by UsulPro** [comment]
@achtan! thank you for this issue, really need to add!
but in the proposed form you we also get the scrollbar in the right pane.
maybe we can insert it somewhere else?

**Comment by achtan** [comment]
to prevent Pane2 form scrolling we can maybe set `overflow: visible` in https://github.com/sm-react/storybook-addon-material-ui/blob/bcce6f0e986a67cc476e792a90d35264714cf72c/src/components/SplitPane/index.js#L177

**Comment by UsulPro** [comment]
Oh, right! we can pass `overflow` through props only for left Pane
`pane1Style={{overflowX: 'auto', overflowY: 'auto'}}`
but I found a few more problems with the pane
so in the future it will need to be redone

**Comment by achtan** [comment]
can u pls fix this asap?

**Comment by UsulPro** [comment]
[v0.7.0](https://github.com/sm-react/storybook-addon-material-ui/releases/tag/0.7.0)
@achtan, you could test that now works as you need?

**Comment by achtan** [comment]
thx, its working!
