### ISSUE TITLE
Create new Theme for Helloween Pumpkin Head

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#31]
1 Open demo [page](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=true&selectedKind=Helloween&selectedStory=Pumpkin%20Head&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

2 Play with settings in the Theme Editor

![image](https://cloud.githubusercontent.com/assets/14885189/19826645/3fc1bb80-9dba-11e6-9528-981f19af0f71.png)

3 Save this theme

![image](https://cloud.githubusercontent.com/assets/14885189/19830926/bc7649b6-9e28-11e6-90c8-c1f328ea8931.png)

4 [make a fork](https://github.com/sm-react/storybook-addon-material-ui/fork)

5 Upload saved theme to `example/LoremMaterial/`

6 Make PR

Done!

**Comment by Radhikadua123** [comment]
Hey! I would like to claim this .Can i get this? Thanks.

**Comment by UsulPro** [comment]
Hi, @Radhikadua123! 
It's open for everybody, just make a PR

**Comment by Radhikadua123** [comment]
I have created the new theme . I am finding it difficult to make a PR.Thanks

**Comment by UsulPro** [comment]
You can specify at what point you are stuck, so I can tell what to do?

**Comment by Radhikadua123** [comment]
I am not getting what to write in the commit so as to have a good commit .I am also confused whether i have to push the saved file to my local repo or should i directly upload it by creating a  branch example/LoremMaterial/ to the master branch.

**Comment by UsulPro** [comment]
After you create your theme via our [demo-app](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=true&selectedKind=Helloween&selectedStory=Pumpkin%20Head&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

you need to download it as a .json file:
![image](https://cloud.githubusercontent.com/assets/14885189/19834837/676c4918-9ea3-11e6-913b-beb153401a83.png)

Then upload this file to your forked repo in [example/LoremMaterial](https://github.com/Radhikadua123/storybook-addon-material-ui/tree/master/example/LoremMaterial)  folder
![image](https://cloud.githubusercontent.com/assets/14885189/19834842/c182a118-9ea3-11e6-85c8-9a96e3a0bc59.png)

When it's done. Submit a PR back to original repo
![image](https://cloud.githubusercontent.com/assets/14885189/19834858/5ac78dac-9ea4-11e6-8fa7-32f36820f7dd.png)

and 

![image](https://cloud.githubusercontent.com/assets/14885189/19834860/7a5f45d8-9ea4-11e6-8bcf-1867dd048915.png)
