### ISSUE TITLE
Still need some more helloween themes

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-addon-material-ui#42]
Need to create a helloween theme via our [demo app](https://sm-react.github.io/storybook-addon-material-ui/?theme-ind=0&theme-sidebar=false&selectedKind=Helloween&selectedStory=Pumpkin%20Head&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

> Notes:
> 1. Use the 'PumpkinFull' theme in the `Theme panel` as a base.
> 2. Set your own `themeName` - it will be displayed name in the list
> 3. Set your own  `themeFile` - it will be downloaded file name
> 4. make creative ![image](https://cloud.githubusercontent.com/assets/14885189/19837705/08bf6bbc-9ef2-11e6-89b0-104208b1854f.png)

![image](https://cloud.githubusercontent.com/assets/14885189/19837659/2288ebbe-9ef1-11e6-924c-9015ce355426.png)

**Comment by hmelenok** [comment]
Hey please check mine Rick and Morty pumpkin theme
