### ISSUE TITLE
meteor support

### ISSUE THREAD

**Issue by Tevinthuku** [sm-react/storybook-addon-material-ui#5]
im using manta and meteor. Im getting this error

![screenshot from 2016-09-30 11-49-50](https://cloud.githubusercontent.com/assets/12128153/18986120/16b7503c-8704-11e6-895a-da7518a9e63d.png)
.
how do i fix this

**Comment by UsulPro** [comment]
@Tevinthuku , could you check do you have [file-loader](https://www.npmjs.com/package/file-loader) modul in your project and appropriate settings in `webpack.config.js` like [here](https://github.com/kadirahq/react-storybook/blob/master/src/server/config/defaults/webpack.config.js#L24)

**Comment by Tevinthuku** [comment]
Its running now but I'm now getting cannot read property emit of null from the storybook interface

**Comment by Tevinthuku** [comment]
![screenshot from 2016-10-03 10-32-43](https://cloud.githubusercontent.com/assets/12128153/19030206/d4e9e22a-8954-11e6-82fe-e7e7b1425763.png)

This is what I mean

**Comment by UsulPro** [comment]
could you as well check for this modul: '@kadira/storybook-addons'?
did you try any other storybook addon (like knobs)?
maybe if you have your project on github we could check it togather

**Comment by Tevinthuku** [comment]
Here is the link
https://gitlab.com/tevinthuku/perspectiveenginewebapp.git

**Comment by Tevinthuku** [comment]
Check the muitheme4 branch

**Comment by UsulPro** [comment]
looks like it's a private project...

**Comment by Tevinthuku** [comment]
Im really sorry about that.. Its fixed now .. check again

**Comment by UsulPro** [comment]
@Tevinthuku I checked your project
I found outdated storybook ver and some small issues
finally you can just start over new project with your files:

- `meteor create simple-todos` and follow this [tutorial](https://www.meteor.com/tutorials/react/creating-an-app)
- install this modules `react`, `react-motion`, `react-motion-ui-pack`, `react-mounter`, `react-tap-event-plugin`,  `material-ui` as dependencies
- `meteor npm i --save-dev @kadira/storybook` and follow this [Guid](https://getstorybook.io/docs/basics/slow-start-guide)
- `meteor npm i --save-dev storybook-addon-material-ui`
- `meteor add kadira:flow-router`
- copy all your folders to new project

now you can start storybook `npm run storybook` and your meteor project `meteor`

I made some fixies to your project so you can look at this **working** version [here](https://gitlab.com/UsulPro/meteor-with-storybook)

Feel free to ask any questions if you have

**Comment by Tevinthuku** [comment]
It worked. Thanks

**Comment by Tevinthuku** [comment]
The storybook addon works just fine. But when it comes to theming of the components. Theming from the routes page does not work when running the app.

You can see this error when you swap the home component with the about component in your demo. `meteor-with-storybook`

```
  FlowRouter.route('/', {
    name: 'Home',
    action() {
      mount(MainLayoutCtx, {
        content: () => (<Home />) // swap this with the about component
      });
    }
  });
```

`
Paper.js:96Uncaught TypeError: Cannot read property 'prepareStyles' of undefined
`

**Comment by UsulPro** [comment]
I've seen some nesting `MuiThemeProvider`-s in your project. I removed some. Better if you check your project structure and finally have something like this:
```
├─> storybok
│    └─ storybook-addon-material-ui
│        └─ Your React Components
│
├─> app
     └─ React Container with MuiThemeProvides
         └─ Your React Components

```
Make shure that you wrapping your components in theme provider only once in the root of components tree and you wrapped all material-ui components

_Maybe we need to have some solution to ease the transition from storybook to application in a **future**_

maybe you can learn something useful [here](https://github.com/kadirahq/react-storybook/issues/24)

**Comment by Tevinthuku** [comment]
I now understand thanks.
