### ISSUE TITLE
Prop warnings for themeName and themeNameArr

### ISSUE THREAD

**Issue by hoschi** [sm-react/storybook-addon-material-ui#50]
I updated my dependcies:
```
-    "@kadira/storybook": "2.20.1",
+    "@kadira/storybook": "2.35.3",
-    "storybook-addon-material-ui": "0.7.2",
+    "storybook-addon-material-ui": "0.7.5",
-    "material-ui": "0.15.4",
+    "material-ui": "0.16.7",
-    "react": "15.3.1",
-    "react-dom": "15.3.1",
+    "react": "15.4.2",
+    "react-dom": "15.4.2",
-    "react-tap-event-plugin": "1.0.0",
+    "react-tap-event-plugin": "2.0.1",
```

Now I get warnings about props not passed to MuiTheme component:
![2017-02-06-171730_1303x1384_scrot](https://cloud.githubusercontent.com/assets/163128/22655339/27b5527a-ec90-11e6-9fa1-cdac1324c9b9.png)

I checked the component https://github.com/sm-react/storybook-addon-material-ui/blob/196e7c4a6bfd0c175666e00da2c7e4aa955b595d/src/containers/MuiTheme.js#L15
But it seems it doesn't do anything with them. Also my theme name and settings are visible in the panes added from your addon.

**Comment by joshjconlin** [comment]
removing both of those props from MuiTheme.js seems to fix the error

**Comment by hoschi** [comment]
sure, the question is: are these props really required or not. My quick code scan give me the opinion they are not used.

**Comment by UsulPro** [comment]
Yes, we don't need them for now.
Thank you!

**Comment by hoschi** [comment]
I'll test it when it is released.

**Comment by UsulPro** [comment]
@hoschi, @joshjconlin! v0.7.6 is avalible on npm. No warnings in console should be

**Comment by hoschi** [comment]
works, thank you
