### ISSUE TITLE
Allow material-ui 0.18.0 compatibility

### ISSUE THREAD

**Issue by mcbain** [sm-react/storybook-addon-material-ui#56]
npm WARN storybook-addon-material-ui@0.7.7 requires a peer of material-ui@^0.15.0 || ^0.16.4 || ^0.17.0 but none was installed.

**Comment by UsulPro** [comment]
Thanks @mcbain 
I think it's time to update peer dependencies!

**Comment by UsulPro** [comment]
fixed in [storybook-addon-material-u@0.7.8](https://github.com/sm-react/storybook-addon-material-ui/releases/tag/0.7.8)
